# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20170112_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='comprador',
        ),
    ]
